SELECT DISTINCT CATEGORY,
       MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE
       FIRST_VALUE(PRODUCT_NAME) OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
